### ISSUE TITLE
NA P-values

### ISSUE THREAD

**Issue by daviddaiweizhang** [yuanzhongshang/PMR#1]
I used PMR_summary_Egger on approximately 1000 different variables, and for 90% of them I received a p-value of NA, though the effect estimate is always non-NA. What went wrong here?

**Comment by yuanzhongshang** [comment]
Thanks for your interest with PMR. In the main function, there is one input parameter called ‘Heritability_geneexpression_threshold’. When the estimate of gene expression heritability explained by cis-SNPs is smaller than the threshold, the pvalue of the causal effect was automatically assigned to be NA value. You can set the 'Heritability_geneexpression_threshold' to be 0 to avoid such NA issue in your analysis.
