### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by jdjmoon** [yuanzhongshang/PMR#5]
Hello,

First, thank you for creating this wonderful package. I have been facing an issue while downloading the package. I was wondering if if I can get some assistance or if there is any alternative to download the package.

Thank you.

P.S. I have attached the error message shown in the console. 

R version 4.3.2 (2023-10-31 ucrt) -- "Eye Holes"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)
> library(devtools)
> install_github("yuanzhongshang/PMR")
Downloading GitHub repo yuanzhongshang/PMR@HEAD
── R CMD build ─────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\jake1\AppData\Local\Temp\RtmpGYnPVx\remotes3938378a7968\yuanzhongshang-PMR-7e49f14/DESCRIPTION' (442ms)
─  preparing 'PMR': (516ms)
✔  checking DESCRIPTION meta-information ...
─  cleaning src
   Warning in cleanup_pkg(pkgdir, Log) :
     unable to run 'make clean' in 'src'
─  installing the package to process help pages
         -----------------------------------
─  installing *source* package 'PMR' ...
   ** using staged installation
   ** libs
   Error in system(paste(MAKE, p1(paste("-f", shQuote(makefiles))), "compilers"),  : 
     'make' not found
─  removing 'C:/Users/jake1/AppData/Local/Temp/RtmpwzPj6b/Rinst3a4061767261/PMR'
         -----------------------------------
   ERROR: package installation failed
에러: Failed to install 'PMR' from GitHub:
  ! System command 'Rcmd.exe' failed

**Comment by yuanzhongshang** [comment]
Hello,

Thank you for your attention. This error indicates that the 'make' command is not found, which is required for building and installing packages with compiled code. To resolve this issue, you may need to install the necessary build tools on your system. If you are using a Windows machine, you can install the 'Rtools' package (https://cran.r-project.org/bin/windows/Rtools/), which provides the required tools including 'make' .

If you have any question, do not hesitate to contact me.

Best,
Zhongshang

**Comment by jdjmoon** [comment]
Thank you for a quick update. I have found out there was a version conflict in RTools.
